kind: pipeline
name: default

steps:
- name: build and push to docker
  image: plugins/kaniko
  settings:
    repo: renothing/mysql
    auto_tag: true
    pull_image: true
    username: 
      from_secret: dockerhub_login
    password:
      from_secret: dockerhub_token
    tags:
    #- latest
     - 8
